name:                dejzi
version:             0.1.0.0
github:              "githubuser/dejzi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dejzi#readme>

dependencies:
- base >= 4.7 && < 5
- Spock
- http-types
- mtl
- text
- lucid
- Spock-lucid
- aeson
- monad-logger
- persistent
- persistent-sqlite
- persistent-template

library:
  source-dirs: src

executables:
  dejzi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dejzi

tests:
  dejzi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dejzi
